### ISSUE TITLE
Following error occurs while running python agegender_demo.py file

### ISSUE THREAD

**Issue by sakhitasree** [abars/YoloKerasFaceDetection#11]
Using TensorFlow backend.
Traceback (most recent call last):
  File "agegender_demo.py", line 377, in <module>
    main(sys.argv[1:])
  File "agegender_demo.py", line 335, in main
    model_face = load_model(MODEL_ROOT_PATH+'yolov2_tiny-face.h5')
  File "/home/sakhita/.local/lib/python2.7/site-packages/keras/models.py", line 128, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/sakhita/.local/lib/python2.7/site-packages/keras/models.py", line 177, in model_from_config
    return layer_from_config(config, custom_objects=custom_objects)
  File "/home/sakhita/.local/lib/python2.7/site-packages/keras/utils/layer_utils.py", line 36, in layer_from_config
    return layer_class.from_config(config['config'])
  File "/home/sakhita/.local/lib/python2.7/site-packages/keras/engine/topology.py", line 2375, in from_config
    process_layer(layer_data)
  File "/home/sakhita/.local/lib/python2.7/site-packages/keras/engine/topology.py", line 2353, in process_layer
    custom_objects=custom_objects)
  File "/home/sakhita/.local/lib/python2.7/site-packages/keras/utils/layer_utils.py", line 36, in layer_from_config
    return layer_class.from_config(config['config'])
  File "/home/sakhita/.local/lib/python2.7/site-packages/keras/engine/topology.py", line 929, in from_config
    return cls(**config)
TypeError: __init__() got an unexpected keyword argument 'dtype'

can anyone please tell me how to correct this.

**Comment by mranosa** [comment]
Try upgrading your h5py dependency
