### ISSUE TITLE
OSError: Unable to open file (file signature not found)

### ISSUE THREAD

**Issue by ekkyu** [abars/YoloKerasFaceDetection#9]
I received this error when I ran 
```
python3 agender_demo.py
```
Please let me know how to solve this.

```
Traceback (most recent call last):
  File "agegender_demo.py", line 376, in <module>
    main(sys.argv[1:])
  File "agegender_demo.py", line 336, in main
    model_age = load_model(MODEL_ROOT_PATH+'agegender_age101_squeezenet.hdf5')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/saving.py", line 417, in load_model
    f = h5dict(filepath, 'r')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/utils/io_utils.py", line 186, in __init__
    self.data = h5py.File(path, mode=mode)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/h5py/_hl/files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
```

**Comment by ReekiLee** [comment]
hello, have u solved it now?  cause i received it too...

**Comment by ekkyu** [comment]
> hello, have u solved it now? cause i received it too...

This code is written in Python2.
I finally used this repo: https://github.com/oarriaga/face_classification

**Comment by ReekiLee** [comment]
> hello, have u solved it now? cause i received it too...
> 
> This code is written in Python2.
> I finally used this repo: https://github.com/oarriaga/face_classification

Thanks !!
but i need to use yolov2-tiny :(
